config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :to_do_items
  root to: "to_do_items#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do_item.rb
class ToDoItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/to_do_items_controller.rb
class ToDoItemsController < ApplicationController
  before_action :set_to_do_item, only: [:show, :edit, :update, :destroy]

  # GET /to_do_items
  # GET /to_do_items.json
  def index
    @to_do_items = ToDoItem.all
  end

  # GET /to_do_items/1
  # GET /to_do_items/1.json
  def show
  end

  # GET /to_do_items/new
  def new
    @to_do_item = ToDoItem.new
  end

  # GET /to_do_items/1/edit
  def edit
  end

  # POST /to_do_items
  # POST /to_do_items.json
  def create
    @to_do_item = ToDoItem.new(to_do_item_params)

    respond_to do |format|
      if @to_do_item.save
        format.html { redirect_to @to_do_item, notice: 'To do item was successfully created.' }
        format.json { render :show, status: :created, location: @to_do_item }
      else
        format.html { render :new }
        format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_do_items/1
  # PATCH/PUT /to_do_items/1.json
  def update
    respond_to do |format|
      if @to_do_item.update(to_do_item_params)
        format.html { redirect_to @to_do_item, notice: 'To do item was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do_item }
      else
        format.html { render :edit }
        format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_items/1
  # DELETE /to_do_items/1.json
  def destroy
    @to_do_item.destroy
    respond_to do |format|
      format.html { redirect_to to_do_items_url, notice: 'To do item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_item
      @to_do_item = ToDoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_item_params
      params.require(:to_do_item).permit(:description, :checked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_do_items/_form.html.erb
<%= form_with(model: to_do_item, local: true) do |form| %>
  <% if to_do_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(to_do_item.errors.count, "error") %> prohibited this to_do_item from being saved:</h2>

      <ul>
      <% to_do_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :checked %>
    <%= form.check_box :checked %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/to_do_items/edit.html.erb
<h1>Editing To Do Item</h1>

<%= render 'form', to_do_item: @to_do_item %>

<%= link_to 'Show', @to_do_item %> |
<%= link_to 'Back', to_do_items_path %>

app/views/to_do_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Do Items</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Checked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_do_items.each do |to_do_item| %>
      <tr>
        <td><%= to_do_item.description %></td>
        <td><%= to_do_item.checked %></td>
        <td><%= link_to 'Show', to_do_item %></td>
        <td><%= link_to 'Edit', edit_to_do_item_path(to_do_item) %></td>
        <td><%= link_to 'Destroy', to_do_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To Do Item', new_to_do_item_path %>

app/views/to_do_items/new.html.erb
<h1>New To Do Item</h1>

<%= render 'form', to_do_item: @to_do_item %>

<%= link_to 'Back', to_do_items_path %>

app/views/to_do_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @to_do_item.description %>
</p>

<p>
  <strong>Checked:</strong>
  <%= @to_do_item.checked %>
</p>

<%= link_to 'Edit', edit_to_do_item_path(@to_do_item) %> |
<%= link_to 'Back', to_do_items_path %>